import { Application } from '../types/application';

export function createEmptyApplication(): Application {
  return {
    id: `app_${Date.now()}`,
    status: 'draft',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    currentStep: 1,
    maxCompletedStep: 1,
    numPrincipals: 1,
    prepopulatedFields: {},
    business: {
      legalName: '',
      hasTradingName: false,
      tradingName: '',
      startDate: '',
      legalEntity: '',
      legalEntityOther: '',
      classification: '',
      productsSold: '',
      physicalAddress: {
        line1: '',
        line2: '',
        city: '',
        county: '',
        postcode: '',
        country: 'United Kingdom',
      },
      isMailingSameAsPhysical: true,
      mailingAddress: {
        line1: '',
        line2: '',
        city: '',
        county: '',
        postcode: '',
        country: 'United Kingdom',
      },
      businessPhone: '',
      mobilePhone: '',
      website: '',
      registrationNumber: '',
      acceptsCardPayments: null,
      posMakeModel: '',
      acquiringBank: '',
      ownershipType: '',
      ownershipLengthYears: null,
      ownershipLengthMonths: null,
      leaseEndDate: '',
      hasLandlordOrMortgage: null,
      landlordMortgageCompany: '',
      landlordMortgageContact: '',
      landlordMortgagePhone: '',
      monthlyRentMortgage: null,
    },
    principals: [
      {
        id: 'principal_1',
        name: '',
        title: '',
        ownershipPercentage: null,
        homeAddress: {
          line1: '',
          line2: '',
          city: '',
          county: '',
          postcode: '',
          country: 'United Kingdom',
        },
        hasLivedThreeYears: null,
        previousAddress: {
          line1: '',
          line2: '',
          city: '',
          county: '',
          postcode: '',
          country: 'United Kingdom',
        },
        previousAddressFrom: '',
        previousAddressTo: '',
        dateOfBirth: '',
        email: '',
        mobilePhone: '',
      },
    ],
    financials: {
      averageMonthlyCardSales: null,
      totalMonthlySales: null,
      annualGrossSales: null,
      overdraftLimit: null,
    },
    funding: {
      requestedAmount: null,
      useOfFunds: '',
      hasExistingLoanOrAdvance: null,
      outstandingBalance: null,
      currentProvider: '',
    },
    managementAccounts: { documents: [] },
    bankStatements: {
      requiredMonths: 6,
      documents: [],
      coverage: {
        months: [],
        consecutiveMonths: 0,
        isComplete: false,
      },
    },
    certification: {
      confirmed: false,
      signatures: [],
    },
    authorisation: {
      confirmed: false,
      signatures: [],
    },
    registeredPrincipals: [],
  };
}

export function createSampleApplication(): Application {
  return {
    id: `app_demo_${Date.now()}`,
    status: 'draft',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    currentStep: 12, // At review step for rapid evaluation
    maxCompletedStep: 12,
    numPrincipals: 2,
    registeredPrincipals: [
      {
        id: 'psc-1',
        name: 'Alistair Ross',
        title: 'Managing Director',
        ownershipPercentage: 75,
        dateOfBirthMonthYear: { month: 7, year: 1982 },
        dateOfBirthFormatted: '24/07/1982',
        homeAddress: {
          line1: 'Suite 3A, 42 St Vincent Street',
          city: 'Glasgow',
          postcode: 'G2 5TS',
          country: 'United Kingdom',
        },
        source: 'Companies House PSC',
        isMajorityController: true,
      },
      {
        id: 'psc-2',
        name: 'Fiona Campbell',
        title: 'Director',
        ownershipPercentage: 25,
        dateOfBirthMonthYear: { month: 11, year: 1986 },
        dateOfBirthFormatted: '12/11/1986',
        homeAddress: {
          line1: 'Suite 3A, 42 St Vincent Street',
          city: 'Glasgow',
          postcode: 'G2 5TS',
          country: 'United Kingdom',
        },
        source: 'Companies House PSC',
        isMajorityController: false,
      },
    ],
    prepopulatedFields: {
      legalName: 'Companies House Verified',
      registrationNumber: 'Companies House Verified',
      startDate: 'Companies House Verified',
      legalEntity: 'Companies House Verified',
      classification: 'Companies House Verified',
      productsSold: 'Companies House Verified',
      physicalAddress: 'Companies House Verified',
      businessPhone: 'Google Places Verified',
      principal_0_name: 'Companies House Verified',
      principal_0_title: 'Companies House Verified',
      principal_0_ownershipPercentage: 'Companies House Verified',
      principal_0_dateOfBirth: 'Companies House Verified',
      website: 'Google Places Verified',
    },
    business: {
      legalName: 'Apex Hospitality Group Ltd',
      hasTradingName: true,
      tradingName: 'The Copper Bistro & Bar',
      startDate: '15/03/2018',
      legalEntity: 'Ltd Co',
      legalEntityOther: '',
      classification: 'Restaurant',
      productsSold: 'Fine artisanal dining, gourmet craft beers, private events catering, and corporate banqueting.',
      physicalAddress: {
        line1: '42 St Vincent Street',
        line2: 'Suite 3A',
        city: 'Glasgow',
        county: 'Lanarkshire',
        postcode: 'G2 5TS',
        country: 'United Kingdom',
      },
      isMailingSameAsPhysical: true,
      mailingAddress: {
        line1: '',
        line2: '',
        city: '',
        county: '',
        postcode: '',
        country: 'United Kingdom',
      },
      businessPhone: '0141 248 9900',
      mobilePhone: '07700 900452',
      website: 'www.copperbistro.co.uk',
      registrationNumber: 'SC589210',
      acceptsCardPayments: true,
      posMakeModel: 'Clover Station Pro / Verifone V200c',
      acquiringBank: 'Barclaycard Payment Solutions',
      ownershipType: 'Lease',
      ownershipLengthYears: 6,
      ownershipLengthMonths: 4,
      leaseEndDate: '31/03/2029',
      hasLandlordOrMortgage: true,
      landlordMortgageCompany: 'Caledonian Commercial Properties Ltd',
      landlordMortgageContact: 'Graeme MacIntyre',
      landlordMortgagePhone: '0141 552 1100',
      monthlyRentMortgage: 4250,
    },
    principals: [
      {
        id: 'principal_1',
        name: 'Alistair Ross',
        title: 'Managing Director',
        ownershipPercentage: 60,
        homeAddress: {
          line1: '14 Kelvin Drive',
          line2: 'Flat 2/1',
          city: 'Glasgow',
          county: 'Glasgow City',
          postcode: 'G20 8QG',
          country: 'United Kingdom',
        },
        hasLivedThreeYears: true,
        previousAddress: {
          line1: '',
          line2: '',
          city: '',
          county: '',
          postcode: '',
          country: 'United Kingdom',
        },
        previousAddressFrom: '',
        previousAddressTo: '',
        dateOfBirth: '24/07/1982',
        email: 'alistair.ross@copperbistro.co.uk',
        mobilePhone: '07700 900452',
      },
      {
        id: 'principal_2',
        name: 'Fiona Campbell',
        title: 'Operations Director',
        ownershipPercentage: 40,
        homeAddress: {
          line1: '8 Queen Margaret Road',
          line2: '',
          city: 'Glasgow',
          county: 'Glasgow City',
          postcode: 'G20 6DP',
          country: 'United Kingdom',
        },
        hasLivedThreeYears: false,
        previousAddress: {
          line1: '55 Byres Road',
          line2: '',
          city: 'Glasgow',
          county: 'Glasgow City',
          postcode: 'G11 5RB',
          country: 'United Kingdom',
        },
        previousAddressFrom: '09/20',
        previousAddressTo: '03/23',
        dateOfBirth: '11/11/1986',
        email: 'fiona.campbell@copperbistro.co.uk',
        mobilePhone: '07700 900789',
      },
    ],
    financials: {
      averageMonthlyCardSales: 48000,
      totalMonthlySales: 62000,
      annualGrossSales: 745000,
      overdraftLimit: 15000,
    },
    funding: {
      requestedAmount: 75000,
      useOfFunds: 'Expansion of outdoor heated terrace and installation of state-of-the-art commercial combi-ovens to expand dining capacity by 40 covers.',
      hasExistingLoanOrAdvance: true,
      outstandingBalance: 12500,
      currentProvider: 'Funding Circle Business Loan',
    },
    managementAccounts: { documents: [] },
    bankStatements: {
      requiredMonths: 6,
      documents: [
        {
          id: 'doc_sample_1',
          fileName: 'Bank_Statement_Oct_2025.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.4,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 10, year: 2025 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'doc_sample_2',
          fileName: 'Bank_Statement_Nov_2025.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.1,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 11, year: 2025 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'doc_sample_3',
          fileName: 'Bank_Statement_Dec_2025.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.6,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 12, year: 2025 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'doc_sample_4',
          fileName: 'Bank_Statement_Jan_2026.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.3,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 1, year: 2026 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'doc_sample_5',
          fileName: 'Bank_Statement_Feb_2026.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.5,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 2, year: 2026 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'doc_sample_6',
          fileName: 'Bank_Statement_Mar_2026.pdf',
          fileType: 'application/pdf',
          fileSize: 1024 * 1024 * 2.8,
          uploadStatus: 'uploaded',
          detectedPeriods: [{ month: 3, year: 2026 }],
          uploadedAt: new Date(Date.now() - 86400000).toISOString(),
        },
      ],
      coverage: {
        months: [
          { month: 10, year: 2025, status: 'covered', documentIds: ['doc_sample_1'] },
          { month: 11, year: 2025, status: 'covered', documentIds: ['doc_sample_2'] },
          { month: 12, year: 2025, status: 'covered', documentIds: ['doc_sample_3'] },
          { month: 1, year: 2026, status: 'covered', documentIds: ['doc_sample_4'] },
          { month: 2, year: 2026, status: 'covered', documentIds: ['doc_sample_5'] },
          { month: 3, year: 2026, status: 'covered', documentIds: ['doc_sample_6'] },
        ],
        consecutiveMonths: 6,
        isComplete: true,
        startDate: { month: 10, year: 2025 },
        endDate: { month: 3, year: 2026 },
      },
    },
    certification: {
      confirmed: true,
      signatures: [
        {
          principalId: 'principal_1',
          principalName: 'Alistair Ross',
          signatureType: 'type',
          signatureData: 'Alistair Ross',
          signedAt: new Date().toISOString(),
        },
        {
          principalId: 'principal_2',
          principalName: 'Fiona Campbell',
          signatureType: 'type',
          signatureData: 'Fiona Campbell',
          signedAt: new Date().toISOString(),
        },
      ],
      signedAt: new Date().toISOString(),
    },
    authorisation: {
      confirmed: true,
      signatures: [
        {
          principalId: 'principal_1',
          principalName: 'Alistair Ross',
          signatureType: 'type',
          signatureData: 'Alistair Ross',
          signedAt: new Date().toISOString(),
        },
        {
          principalId: 'principal_2',
          principalName: 'Fiona Campbell',
          signatureType: 'type',
          signatureData: 'Fiona Campbell',
          signedAt: new Date().toISOString(),
        },
      ],
      signedAt: new Date().toISOString(),
    },
  };
}
